name: DimensionCreator
version: '1'
main: dimensioncreator.dimensioncreator.DimensionCreator
api-version: 1.19
authors: [ SakakiAruka ]
description: generate custom dimension
website: https://github.com/Sakaki-Aruka
commands:
  dc:
    permission: dimensioncreator.op

permissions:
  dimensioncreator.op:
    default: op